/* Generated by Snowball 2.0.0 - https://snowballstem.org/ */

#include "header.h"

#ifdef __cplusplus
extern "C" {
#endif
extern int czech_UTF_8_stem(struct SN_env * z);
#ifdef __cplusplus
}
#endif
static int r_case_suffix(struct SN_env * z);
static int r_possessive_suffix(struct SN_env * z);
static int r_mark_regions(struct SN_env * z);
static int r_palatalise_i(struct SN_env * z);
static int r_palatalise_e(struct SN_env * z);
static int r_R1(struct SN_env * z);
#ifdef __cplusplus
extern "C" {
#endif


extern struct SN_env * czech_UTF_8_create_env(void);
extern void czech_UTF_8_close_env(struct SN_env * z);


#ifdef __cplusplus
}
#endif
static const symbol s_0_0[1] = { 'c' };
static const symbol s_0_1[2] = { 'n', 'c' };
static const symbol s_0_2[4] = { 0xC3, 0xAD, 'n', 'c' };
static const symbol s_0_3[3] = { 'a', 'v', 'c' };
static const symbol s_0_4[3] = { 'o', 'v', 'c' };

static const struct among a_0[5] =
{
/*  0 */ { 1, s_0_0, -1, 1, 0},
/*  1 */ { 2, s_0_1, 0, -1, 0},
/*  2 */ { 4, s_0_2, 1, 2, 0},
/*  3 */ { 3, s_0_3, 0, -1, 0},
/*  4 */ { 3, s_0_4, 0, -1, 0}
};

static const symbol s_1_0[1] = { 'c' };
static const symbol s_1_1[2] = { 'n', 'c' };
static const symbol s_1_2[4] = { 0xC3, 0xAD, 'n', 'c' };
static const symbol s_1_3[3] = { 'a', 'v', 'c' };
static const symbol s_1_4[3] = { 'o', 'v', 'c' };
static const symbol s_1_5[3] = { 0xC4, 0x8D, 't' };
static const symbol s_1_6[3] = { 0xC5, 0xA1, 't' };
static const symbol s_1_7[5] = { 'd', 'e', 0xC5, 0xA1, 't' };
static const symbol s_1_8[5] = { 'l', 'e', 0xC5, 0xA1, 't' };
static const symbol s_1_9[4] = { 'i', 0xC5, 0xA1, 't' };
static const symbol s_1_10[6] = { 'p', 'o', 'u', 0xC5, 0xA1, 't' };
static const symbol s_1_11[5] = { 0xC3, 0xA1, 0xC5, 0xA1, 't' };
static const symbol s_1_12[5] = { 0xC3, 0xAD, 0xC5, 0xA1, 't' };

static const struct among a_1[13] =
{
/*  0 */ { 1, s_1_0, -1, 1, 0},
/*  1 */ { 2, s_1_1, 0, -1, 0},
/*  2 */ { 4, s_1_2, 1, 2, 0},
/*  3 */ { 3, s_1_3, 0, -1, 0},
/*  4 */ { 3, s_1_4, 0, -1, 0},
/*  5 */ { 3, s_1_5, -1, 3, 0},
/*  6 */ { 3, s_1_6, -1, 4, 0},
/*  7 */ { 5, s_1_7, 6, -1, 0},
/*  8 */ { 5, s_1_8, 6, -1, 0},
/*  9 */ { 4, s_1_9, 6, -1, 0},
/* 10 */ { 6, s_1_10, 6, -1, 0},
/* 11 */ { 5, s_1_11, 6, -1, 0},
/* 12 */ { 5, s_1_12, 6, -1, 0}
};

static const symbol s_2_0[2] = { 'i', 'n' };
static const symbol s_2_1[2] = { 'o', 'v' };
static const symbol s_2_2[3] = { 0xC5, 0xAF, 'v' };

static const struct among a_2[3] =
{
/*  0 */ { 2, s_2_0, -1, 2, 0},
/*  1 */ { 2, s_2_1, -1, 1, 0},
/*  2 */ { 3, s_2_2, -1, 1, 0}
};

static const symbol s_3_1[1] = { 'l' };
static const symbol s_3_2[2] = { 't', 'l' };
static const symbol s_3_3[1] = { 's' };
static const symbol s_3_4[2] = { 'e', 's' };
static const symbol s_3_5[2] = { 0xC4, 0x8D };
static const symbol s_3_6[3] = { 'e', 0xC4, 0x8D };
static const symbol s_3_7[2] = { 0xC5, 0x99 };
static const symbol s_3_8[2] = { 0xC5, 0xBE };

static const struct among a_3[9] =
{
/*  0 */ { 0, 0, -1, 2, 0},
/*  1 */ { 1, s_3_1, 0, 1, 0},
/*  2 */ { 2, s_3_2, 1, 2, 0},
/*  3 */ { 1, s_3_3, 0, 1, 0},
/*  4 */ { 2, s_3_4, 3, 2, 0},
/*  5 */ { 2, s_3_5, 0, 1, 0},
/*  6 */ { 3, s_3_6, 5, 2, 0},
/*  7 */ { 2, s_3_7, 0, 1, 0},
/*  8 */ { 2, s_3_8, 0, 1, 0}
};

static const symbol s_4_0[3] = { 'o', 'b', 'l' };
static const symbol s_4_1[2] = { 's', 'n' };
static const symbol s_4_2[3] = { 'd', 'o', 't' };

static const struct among a_4[3] =
{
/*  0 */ { 3, s_4_0, -1, -1, 0},
/*  1 */ { 2, s_4_1, -1, -1, 0},
/*  2 */ { 3, s_4_2, -1, -1, 0}
};

static const symbol s_5_0[2] = { 'u', 'c' };
static const symbol s_5_1[1] = { 'h' };
static const symbol s_5_2[2] = { 'o', 'k' };
static const symbol s_5_3[3] = { 'k', 'a', 'r' };
static const symbol s_5_4[2] = { 0xC4, 0x8D };

static const struct among a_5[5] =
{
/*  0 */ { 2, s_5_0, -1, -1, 0},
/*  1 */ { 1, s_5_1, -1, -1, 0},
/*  2 */ { 2, s_5_2, -1, -1, 0},
/*  3 */ { 3, s_5_3, -1, -1, 0},
/*  4 */ { 2, s_5_4, -1, -1, 0}
};

static const symbol s_6_0[1] = { 'a' };
static const symbol s_6_1[3] = { 'a', 'm', 'a' };
static const symbol s_6_2[3] = { 'a', 't', 'a' };
static const symbol s_6_3[2] = { 'e', 'b' };
static const symbol s_6_4[2] = { 'e', 'c' };
static const symbol s_6_5[1] = { 'e' };
static const symbol s_6_6[3] = { 'e', 't', 'e' };
static const symbol s_6_7[4] = { 0xC4, 0x9B, 't', 'e' };
static const symbol s_6_8[3] = { 'e', 'c', 'h' };
static const symbol s_6_9[5] = { 'a', 't', 'e', 'c', 'h' };
static const symbol s_6_10[4] = { 0xC3, 0xA1, 'c', 'h' };
static const symbol s_6_11[4] = { 0xC3, 0xAD, 'c', 'h' };
static const symbol s_6_12[4] = { 0xC3, 0xBD, 'c', 'h' };
static const symbol s_6_13[1] = { 'i' };
static const symbol s_6_14[2] = { 'm', 'i' };
static const symbol s_6_15[3] = { 'a', 'm', 'i' };
static const symbol s_6_16[3] = { 'e', 'm', 'i' };
static const symbol s_6_17[4] = { 0xC4, 0x9B, 'm', 'i' };
static const symbol s_6_18[4] = { 0xC5, 0xA5, 'm', 'i' };
static const symbol s_6_19[4] = { 0xC3, 0xAD, 'm', 'i' };
static const symbol s_6_20[4] = { 0xC3, 0xBD, 'm', 'i' };
static const symbol s_6_21[3] = { 'e', 't', 'i' };
static const symbol s_6_22[4] = { 0xC4, 0x9B, 't', 'i' };
static const symbol s_6_23[3] = { 'o', 'v', 'i' };
static const symbol s_6_24[2] = { 'e', 'k' };
static const symbol s_6_25[3] = { 0xC4, 0x9B, 'k' };
static const symbol s_6_26[2] = { 'e', 'm' };
static const symbol s_6_27[4] = { 'e', 't', 'e', 'm' };
static const symbol s_6_28[5] = { 0xC4, 0x9B, 't', 'e', 'm' };
static const symbol s_6_29[3] = { 0xC4, 0x9B, 'm' };
static const symbol s_6_30[3] = { 0xC3, 0xA1, 'm' };
static const symbol s_6_31[3] = { 0xC3, 0xA9, 'm' };
static const symbol s_6_32[3] = { 0xC3, 0xAD, 'm' };
static const symbol s_6_33[3] = { 0xC5, 0xAF, 'm' };
static const symbol s_6_34[5] = { 'a', 't', 0xC5, 0xAF, 'm' };
static const symbol s_6_35[3] = { 0xC3, 0xBD, 'm' };
static const symbol s_6_36[1] = { 'o' };
static const symbol s_6_37[4] = { 0xC3, 0xA9, 'h', 'o' };
static const symbol s_6_38[4] = { 0xC3, 0xAD, 'h', 'o' };
static const symbol s_6_39[2] = { 'u', 's' };
static const symbol s_6_40[2] = { 'a', 't' };
static const symbol s_6_41[2] = { 'e', 't' };
static const symbol s_6_42[1] = { 'u' };
static const symbol s_6_43[4] = { 0xC3, 0xA9, 'm', 'u' };
static const symbol s_6_44[4] = { 0xC3, 0xAD, 'm', 'u' };
static const symbol s_6_45[2] = { 'o', 'u' };
static const symbol s_6_46[2] = { 'e', 'v' };
static const symbol s_6_47[1] = { 'y' };
static const symbol s_6_48[3] = { 'a', 't', 'y' };
static const symbol s_6_49[3] = { 'e', 0xC5, 0x88 };
static const symbol s_6_50[2] = { 0xC4, 0x9B };
static const symbol s_6_51[2] = { 0xC3, 0xA1 };
static const symbol s_6_52[2] = { 0xC5, 0xA5 };
static const symbol s_6_53[2] = { 0xC3, 0xA9 };
static const symbol s_6_54[4] = { 'o', 'v', 0xC3, 0xA9 };
static const symbol s_6_55[2] = { 0xC3, 0xAD };
static const symbol s_6_56[2] = { 0xC5, 0xAF };
static const symbol s_6_57[2] = { 0xC3, 0xBD };

static const struct among a_6[58] =
{
/*  0 */ { 1, s_6_0, -1, 1, 0},
/*  1 */ { 3, s_6_1, 0, 1, 0},
/*  2 */ { 3, s_6_2, 0, 1, 0},
/*  3 */ { 2, s_6_3, -1, 4, 0},
/*  4 */ { 2, s_6_4, -1, 5, 0},
/*  5 */ { 1, s_6_5, -1, 2, 0},
/*  6 */ { 3, s_6_6, 5, 3, 0},
/*  7 */ { 4, s_6_7, 5, 1, 0},
/*  8 */ { 3, s_6_8, -1, 2, 0},
/*  9 */ { 5, s_6_9, 8, 1, 0},
/* 10 */ { 4, s_6_10, -1, 1, 0},
/* 11 */ { 4, s_6_11, -1, 12, 0},
/* 12 */ { 4, s_6_12, -1, 1, 0},
/* 13 */ { 1, s_6_13, -1, 12, 0},
/* 14 */ { 2, s_6_14, 13, 1, 0},
/* 15 */ { 3, s_6_15, 14, 1, 0},
/* 16 */ { 3, s_6_16, 14, 2, 0},
/* 17 */ { 4, s_6_17, 14, 1, 0},
/* 18 */ { 4, s_6_18, 14, 11, 0},
/* 19 */ { 4, s_6_19, 14, 12, 0},
/* 20 */ { 4, s_6_20, 14, 1, 0},
/* 21 */ { 3, s_6_21, 13, 3, 0},
/* 22 */ { 4, s_6_22, 13, 1, 0},
/* 23 */ { 3, s_6_23, 13, 1, 0},
/* 24 */ { 2, s_6_24, -1, 6, 0},
/* 25 */ { 3, s_6_25, -1, 7, 0},
/* 26 */ { 2, s_6_26, -1, 2, 0},
/* 27 */ { 4, s_6_27, 26, 3, 0},
/* 28 */ { 5, s_6_28, 26, 1, 0},
/* 29 */ { 3, s_6_29, -1, 1, 0},
/* 30 */ { 3, s_6_30, -1, 1, 0},
/* 31 */ { 3, s_6_31, -1, 1, 0},
/* 32 */ { 3, s_6_32, -1, 12, 0},
/* 33 */ { 3, s_6_33, -1, 1, 0},
/* 34 */ { 5, s_6_34, 33, 1, 0},
/* 35 */ { 3, s_6_35, -1, 1, 0},
/* 36 */ { 1, s_6_36, -1, 1, 0},
/* 37 */ { 4, s_6_37, 36, 1, 0},
/* 38 */ { 4, s_6_38, 36, 12, 0},
/* 39 */ { 2, s_6_39, -1, 1, 0},
/* 40 */ { 2, s_6_40, -1, 1, 0},
/* 41 */ { 2, s_6_41, -1, 9, 0},
/* 42 */ { 1, s_6_42, -1, 1, 0},
/* 43 */ { 4, s_6_43, 42, 1, 0},
/* 44 */ { 4, s_6_44, 42, 12, 0},
/* 45 */ { 2, s_6_45, 42, 1, 0},
/* 46 */ { 2, s_6_46, -1, 10, 0},
/* 47 */ { 1, s_6_47, -1, 1, 0},
/* 48 */ { 3, s_6_48, 47, 1, 0},
/* 49 */ { 3, s_6_49, -1, 8, 0},
/* 50 */ { 2, s_6_50, -1, 1, 0},
/* 51 */ { 2, s_6_51, -1, 1, 0},
/* 52 */ { 2, s_6_52, -1, 11, 0},
/* 53 */ { 2, s_6_53, -1, 1, 0},
/* 54 */ { 4, s_6_54, 53, 1, 0},
/* 55 */ { 2, s_6_55, -1, 12, 0},
/* 56 */ { 2, s_6_56, -1, 1, 0},
/* 57 */ { 2, s_6_57, -1, 1, 0}
};

static const unsigned char g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 4, 18, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64 };

static const unsigned char g_v_or_syllabic_c[] = { 17, 73, 18, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 4, 18, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64 };

static const unsigned char g_ev_ending[] = { 73, 20, 4 };

static const unsigned char g_env_ending[] = { 71, 66, 23, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 16 };

static const symbol s_0[] = { 'k' };
static const symbol s_1[] = { 0xC3, 0xAD, 'n', 'k' };
static const symbol s_2[] = { 'k' };
static const symbol s_3[] = { 0xC3, 0xAD, 'n', 'k' };
static const symbol s_4[] = { 'c', 'k' };
static const symbol s_5[] = { 's', 'k' };
static const symbol s_6[] = { 'e', 't' };
static const symbol s_7[] = { 't', 0xC5, 0x99 };
static const symbol s_8[] = { 'b' };
static const symbol s_9[] = { 'c' };
static const symbol s_10[] = { 'k' };
static const symbol s_11[] = { 0xC5, 0x88, 'k' };
static const symbol s_12[] = { 'n' };
static const symbol s_13[] = { 't' };
static const symbol s_14[] = { 'v' };
static const symbol s_15[] = { 't' };

static int r_mark_regions(struct SN_env * z) { /* forwardmode */
    {   int c_test1 = z->c; /* test, line 57 */
        {   int ret = skip_utf8(z->p, z->c, 0, z->l, + 3); /* hop, line 57 */
            if (ret < 0) return 0;
            z->c = ret;
        }
        z->I[1] = z->c; /* setmark x, line 57 */
        z->c = c_test1;
    }
    z->I[0] = z->l; /* $p1 = <integer expression>, line 59 */
    {   int c2 = z->c; /* do, line 60 */
        {   int c3 = z->c; /* or, line 73 */
            if (in_grouping_U(z, g_v, 97, 367, 0)) goto lab2; /* grouping v, line 73 */
            goto lab1;
        lab2:
            z->c = c3;
            {   int ret = skip_utf8(z->p, z->c, 0, z->l, 1);
                if (ret < 0) goto lab0;
                z->c = ret; /* next, line 73 */
            }
            {    /* gopast */ /* grouping v_or_syllabic_c, line 73 */
                int ret = out_grouping_U(z, g_v_or_syllabic_c, 97, 367, 1);
                if (ret < 0) goto lab0;
                z->c += ret;
            }
        }
    lab1:
        {    /* gopast */ /* non v, line 73 */
            int ret = in_grouping_U(z, g_v, 97, 367, 1);
            if (ret < 0) goto lab0;
            z->c += ret;
        }
        z->I[0] = z->c; /* setmark p1, line 74 */
        /* try, line 75 */
        if (!(z->I[0] < z->I[1])) goto lab3; /* $(<integer expression> < <integer expression>), line 75 */
        z->I[0] = z->I[1]; /* $p1 = <integer expression>, line 75 */
    lab3:
    lab0:
        z->c = c2;
    }
    return 1;
}

static int r_R1(struct SN_env * z) { /* backwardmode */
    if (!(z->I[0] <= z->c)) return 0; /* $(<integer expression> <= <integer expression>), line 81 */
    return 1;
}

static int r_palatalise_e(struct SN_env * z) { /* backwardmode */
    int among_var;
    z->ket = z->c; /* [, line 84 */
    if (z->c <= z->lb || z->p[z->c - 1] != 99) return 0; /* substring, line 84 */
    among_var = find_among_b(z, a_0, 5);
    if (!(among_var)) return 0;
    z->bra = z->c; /* ], line 84 */
    switch (among_var) { /* among, line 84 */
        case 1:
            {   int ret = slice_from_s(z, 1, s_0); /* <-, line 87 */
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 4, s_1); /* <-, line 93 */
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_palatalise_i(struct SN_env * z) { /* backwardmode */
    int among_var;
    z->ket = z->c; /* [, line 98 */
    if (z->c <= z->lb || (z->p[z->c - 1] != 99 && z->p[z->c - 1] != 116)) return 0; /* substring, line 98 */
    among_var = find_among_b(z, a_1, 13);
    if (!(among_var)) return 0;
    z->bra = z->c; /* ], line 98 */
    switch (among_var) { /* among, line 98 */
        case 1:
            {   int ret = slice_from_s(z, 1, s_2); /* <-, line 101 */
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 4, s_3); /* <-, line 107 */
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int ret = slice_from_s(z, 2, s_4); /* <-, line 109 */
                if (ret < 0) return ret;
            }
            break;
        case 4:
            {   int ret = slice_from_s(z, 2, s_5); /* <-, line 113 */
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_possessive_suffix(struct SN_env * z) { /* backwardmode */
    int among_var;
    z->ket = z->c; /* [, line 125 */
    if (z->c - 1 <= z->lb || (z->p[z->c - 1] != 110 && z->p[z->c - 1] != 118)) return 0; /* substring, line 125 */
    among_var = find_among_b(z, a_2, 3);
    if (!(among_var)) return 0;
    z->bra = z->c; /* ], line 125 */
    {   int ret = r_R1(z); /* call R1, line 125 */
        if (ret <= 0) return ret;
    }
    switch (among_var) { /* among, line 125 */
        case 1:
            {   int ret = slice_del(z); /* delete, line 127 */
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_del(z); /* delete, line 130 */
                if (ret < 0) return ret;
            }
            {   int m1 = z->l - z->c; (void)m1; /* try, line 131 */
                {   int ret = r_palatalise_i(z); /* call palatalise_i, line 131 */
                    if (ret == 0) { z->c = z->l - m1; goto lab0; }
                    if (ret < 0) return ret;
                }
            lab0:
                ;
            }
            break;
    }
    return 1;
}

static int r_case_suffix(struct SN_env * z) { /* backwardmode */
    int among_var;

    {   int mlimit1; /* setlimit, line 137 */
        if (z->c < z->I[0]) return 0;
        mlimit1 = z->lb; z->lb = z->I[0];
        z->ket = z->c; /* [, line 137 */
        among_var = find_among_b(z, a_6, 58); /* substring, line 137 */
        if (!(among_var)) { z->lb = mlimit1; return 0; }
        z->bra = z->c; /* ], line 137 */
        z->lb = mlimit1;
    }
    switch (among_var) { /* among, line 137 */
        case 1:
            {   int ret = slice_del(z); /* delete, line 145 */
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_del(z); /* delete, line 153 */
                if (ret < 0) return ret;
            }
            {   int m2 = z->l - z->c; (void)m2; /* try, line 154 */
                {   int ret = r_palatalise_e(z); /* call palatalise_e, line 154 */
                    if (ret == 0) { z->c = z->l - m2; goto lab0; }
                    if (ret < 0) return ret;
                }
            lab0:
                ;
            }
            break;
        case 3:
            among_var = find_among_b(z, a_3, 9); /* among, line 159 */
            if (!(among_var)) return 0;
            switch (among_var) { /* among, line 159 */
                case 1:
                    {   int ret = slice_del(z); /* delete, line 165 */
                        if (ret < 0) return ret;
                    }
                    break;
                case 2:
                    {   int ret = slice_from_s(z, 2, s_6); /* <-, line 173 */
                        if (ret < 0) return ret;
                    }
                    break;
            }
            break;
        case 4:
            {   int m_test3 = z->l - z->c; /* test, line 179 */
                if (out_grouping_b_U(z, g_v, 97, 367, 0)) return 0; /* non v, line 179 */
                z->c = z->l - m_test3;
            }
            {   int m4 = z->l - z->c; (void)m4; /* not, line 180 */
                if (!(eq_s_b(z, 3, s_7))) goto lab1; /* literal, line 180 */
                return 0;
            lab1:
                z->c = z->l - m4;
            }
            {   int ret = slice_from_s(z, 1, s_8); /* <-, line 181 */
                if (ret < 0) return ret;
            }
            break;
        case 5:
            {   int m_test5 = z->l - z->c; /* test, line 185 */
                if (out_grouping_b_U(z, g_v, 97, 367, 0)) return 0; /* non v, line 185 */
                z->c = z->l - m_test5;
            }
            {   int ret = slice_del(z); /* delete, line 186 */
                if (ret < 0) return ret;
            }
            {   int ret;
                ret = insert_s(z, z->c, z->c, 1, s_9); /* attach, line 186 */
                if (ret < 0) return ret;
            }
            {   int m6 = z->l - z->c; (void)m6; /* try, line 187 */
                {   int ret = r_palatalise_e(z); /* call palatalise_e, line 187 */
                    if (ret == 0) { z->c = z->l - m6; goto lab2; }
                    if (ret < 0) return ret;
                }
            lab2:
                ;
            }
            break;
        case 6:
            {   int m_test7 = z->l - z->c; /* test, line 191 */
                if (out_grouping_b_U(z, g_v, 97, 367, 0)) return 0; /* non v, line 191 */
                z->c = z->l - m_test7;
            }
            {   int m8 = z->l - z->c; (void)m8; /* not, line 192 */
                if (z->c - 1 <= z->lb || z->p[z->c - 1] >> 5 != 3 || !((1069056 >> (z->p[z->c - 1] & 0x1f)) & 1)) goto lab3; /* among, line 192 */
                if (!(find_among_b(z, a_4, 3))) goto lab3;
                return 0;
            lab3:
                z->c = z->l - m8;
            }
            {   int ret = slice_from_s(z, 1, s_10); /* <-, line 197 */
                if (ret < 0) return ret;
            }
            break;
        case 7:
            if (z->c <= z->lb || z->p[z->c - 1] != 'n') return 0; /* literal, line 201 */
            z->c--;
            z->bra = z->c; /* ], line 201 */
            {   int ret = slice_from_s(z, 3, s_11); /* <-, line 201 */
                if (ret < 0) return ret;
            }
            break;
        case 8:
            {   int m_test9 = z->l - z->c; /* test, line 205 */
                if (in_grouping_b_U(z, g_env_ending, 98, 382, 0)) return 0; /* grouping env_ending, line 205 */
                z->c = z->l - m_test9;
            }
            {   int ret = slice_from_s(z, 1, s_12); /* <-, line 206 */
                if (ret < 0) return ret;
            }
            break;
        case 9:
            if (!(find_among_b(z, a_5, 5))) return 0; /* among, line 221 */
            {   int ret = slice_from_s(z, 1, s_13); /* <-, line 228 */
                if (ret < 0) return ret;
            }
            break;
        case 10:
            if (in_grouping_b_U(z, g_ev_ending, 104, 122, 0)) return 0; /* grouping ev_ending, line 232 */
            {   int ret = slice_from_s(z, 1, s_14); /* <-, line 233 */
                if (ret < 0) return ret;
            }
            break;
        case 11:
            {   int ret = slice_from_s(z, 1, s_15); /* <-, line 237 */
                if (ret < 0) return ret;
            }
            break;
        case 12:
            {   int ret = slice_del(z); /* delete, line 242 */
                if (ret < 0) return ret;
            }
            {   int m10 = z->l - z->c; (void)m10; /* try, line 243 */
                {   int ret = r_palatalise_i(z); /* call palatalise_i, line 243 */
                    if (ret == 0) { z->c = z->l - m10; goto lab4; }
                    if (ret < 0) return ret;
                }
            lab4:
                ;
            }
            break;
    }
    return 1;
}

extern int czech_UTF_8_stem(struct SN_env * z) { /* forwardmode */
    {   int ret = r_mark_regions(z); /* call mark_regions, line 250 */
        if (ret <= 0) return ret;
    }
    z->lb = z->c; z->c = z->l; /* backwards, line 251 */

    {   int m1 = z->l - z->c; (void)m1; /* do, line 252 */
        {   int ret = r_case_suffix(z); /* call case_suffix, line 252 */
            if (ret < 0) return ret;
        }
        z->c = z->l - m1;
    }
    {   int m2 = z->l - z->c; (void)m2; /* do, line 253 */
        {   int ret = r_possessive_suffix(z); /* call possessive_suffix, line 253 */
            if (ret < 0) return ret;
        }
        z->c = z->l - m2;
    }
    z->c = z->lb;
    return 1;
}

extern struct SN_env * czech_UTF_8_create_env(void) { return SN_create_env(0, 2, 0); }

extern void czech_UTF_8_close_env(struct SN_env * z) { SN_close_env(z, 0); }

